SetVisible
SetCustomSize   ( 24` 24` )
SetAlpha        ( 30` )
SetTexelOffset  ( 0` -10` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha        ( 50` )
SetTexelOffset  ( 0` -8` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha        ( 80` )
SetTexelOffset  ( 0` -6` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha        ( 120` )
SetTexelOffset  ( 0` -5` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha        ( 170` )
SetTexelOffset  ( 0` -4` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha        ( 200` )
SetTexelOffset  ( 0` -3` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha        ( 220` )
SetTexelOffset  ( 0` -2` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha        ( 240` )
SetTexelOffset  ( 0` -1` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_smash )
SetAlpha        ( 255` )
SetTexelOffset  ( 0` 0` )
Loop
	SetCI           ( 60` ~ImageCI:ui/battle/status/bonus_smash )
Restart
End
