SetVisible
SetCustomSize   ( 24` 24` )
SetAlpha        ( 240` )
SetTexelOffset  ( 0` -1` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_jump )
SetAlpha        ( 220` )
SetTexelOffset  ( -3` -3` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_jump )
SetAlpha        ( 200` )
SetTexelOffset  ( -6` -5` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_jump )
SetAlpha        ( 170` )
SetTexelOffset  ( -8` -6` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_jump )
SetAlpha        ( 120` )
SetTexelOffset  ( -10` -5` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_jump )
SetAlpha        ( 80` )
SetTexelOffset  ( -12` -3` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_jump )
SetAlpha        ( 50` )
SetTexelOffset  ( -13` 0` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_jump )
SetAlpha        ( 30` )
SetTexelOffset  ( -14` 4` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_jump )
SetTexelOffset  ( -15` 9` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_jump )
SetTexelOffset  ( -15` 15` )
SetCI           ( 1` ~ImageCI:ui/battle/status/bonus_jump )
End
