SetVisible
SetCustomSize   ( 16` 16` )
SetAlpha        ( 255` )
SetTexelOffset  ( 0` 0` )
SetCI           ( 1` ~ImageCI:ui/battle/status/dizzy_1 )
SetAlpha        ( 240` )
SetTexelOffset  ( 1` -1` )
SetCI           ( 1` ~ImageCI:ui/battle/status/dizzy_1 )
SetAlpha        ( 220` )
SetTexelOffset  ( 2` -2` )
SetCI           ( 1` ~ImageCI:ui/battle/status/dizzy_1 )
SetAlpha        ( 200` )
SetTexelOffset  ( 3` -3` )
SetCI           ( 1` ~ImageCI:ui/battle/status/dizzy_1 )
SetAlpha        ( 170` )
SetTexelOffset  ( 4` -4` )
SetCI           ( 1` ~ImageCI:ui/battle/status/dizzy_1 )
SetAlpha        ( 120` )
SetTexelOffset  ( 5` -5` )
SetCI           ( 1` ~ImageCI:ui/battle/status/dizzy_1 )
SetAlpha        ( 80` )
SetTexelOffset  ( 6` -6` )
SetCI           ( 1` ~ImageCI:ui/battle/status/dizzy_1 )
SetAlpha        ( 50` )
SetTexelOffset  ( 8` -8` )
SetCI           ( 1` ~ImageCI:ui/battle/status/dizzy_1 )
SetAlpha        ( 30` )
SetTexelOffset  ( 10` -10` )
SetCI           ( 1` ~ImageCI:ui/battle/status/dizzy_1 )
End
