SetVisible
SetTileSize     ( .IconSize:24x24 )
Loop
	SetTexelOffset  ( 0` -1` )
	SetIcon         ( 1` ~ImageIcon:item/anim/hand_0 )
	SetTexelOffset  ( 0` -1` )
	SetIcon         ( 1` ~ImageIcon:item/anim/hand_0 )
	SetTexelOffset  ( 0` -1` )
	SetIcon         ( 1` ~ImageIcon:item/anim/hand_0 )
	SetTexelOffset  ( 0` -1` )
	SetIcon         ( 1` ~ImageIcon:item/anim/hand_0 )
	SetTexelOffset  ( 2` -1` )
	SetIcon         ( 1` ~ImageIcon:item/anim/hand_1 )
	SetTexelOffset  ( 2` -1` )
	SetIcon         ( 1` ~ImageIcon:item/anim/hand_2 )
	SetTexelOffset  ( 2` -1` )
	SetIcon         ( 4` ~ImageIcon:item/anim/hand_3 )
	SetTexelOffset  ( 2` 4` )
	SetIcon         ( 1` ~ImageIcon:item/anim/hand_1 )
	SetTexelOffset  ( 0` 3` )
	SetIcon         ( 1` ~ImageIcon:item/anim/hand_0 )
	SetTexelOffset  ( 0` -1` )
	SetIcon         ( 14` ~ImageIcon:item/anim/hand_4 )
Restart
End
